version: '3'

services:
  rainbow-hasher:
    image: tchaudhry/rainbow-hasher:SHA256
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - 9999:9999
    environment:
      - REDIS_HOST=redis
    networks:
      - app
  
  redis:
    image: "redis"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - app

networks:
  app:
